### ISSUE TITLE
Cap the amount of fires

### ISSUE THREAD

**Issue by CallumDawson** [SanAndreasNoLimits/SANLRPG#119]
Over 24 hours the entire map is flooded with fires.

**Comment by VenomSANL** [comment]
cap what do you mean?
the rounds?

**Comment by VenomSANL** [comment]
Ohh fire, I guess you can search for a script called FIre ;p

**Comment by VenomSANL** [comment]
I think it's the Weather

**Comment by 1B0Y** [comment]
Set a maximum of fires, and remove the old ones ;)

**Comment by CallumDawson** [comment]
I'll make it so we just stop spawning fires after so many, let's say 30 fires.
