### ISSUE TITLE
Update to the nametag statuses

### ISSUE THREAD

**Issue by 1B0Y** [SanAndreasNoLimits/SANLRPG#125]
Due to some of our players running MTA in window mode (as I do), the "Minimized" state does not display as the client isn't actually minimized. The feature will need to be updated so it also works on the "Focused" state as well.

**Comment by CallumDawson** [comment]
Is there such a function/event?

**Comment by 1B0Y** [comment]
...Apparently not. Got them mixed up with the browser functionality. Damn.
