### ISSUE TITLE
Restrict Police Officer job to require at least 5 minutes of playtime

### ISSUE THREAD

**Issue by CallumDawson** [SanAndreasNoLimits/SANLRPG#137]
To prevent 90% of the server being random newbies playing as Police Officers.

**Comment by 1B0Y** [comment]
We could probably upgrade the system so that some jobs require at least a certain limit of playtime before becoming that job.

**Comment by CallumDawson** [comment]
Yeah, I was going to add an extra 'minPlaytime' parameter to jobs. Can you think of any other jobs which might need a minimum playtime?

**Comment by 1B0Y** [comment]
Already added it. Added syntax into jobTables as well ;)
