### ISSUE TITLE
Cinematic text for respawning is too large for 640x480

### ISSUE THREAD

**Issue by CallumDawson** [SanAndreasNoLimits/SANLRPG#28]
The text goes off the screen due to it's length.

**Comment by 1B0Y** [comment]
Who on earth would play at such a small resolution?!

**Comment by 1B0Y** [comment]
Pushed some experimental code. Hopefully this solves the issue. Can't test til Brodie comes back online.

**Comment by 1B0Y** [comment]
Fixed.
