### ISSUE TITLE
Fix position of new messagebox

### ISSUE THREAD

**Issue by CallumDawson** [SanAndreasNoLimits/SANLRPG#66]
It needs to appear vertically in the middle of the screen, to avoid overlap with the chatbox on smaller resolutions.

**Comment by Samer61** [comment]
Why not make it show at the top of the screen? Just a suggestion for now.

**Comment by CallumDawson** [comment]
That's an idea. Would the top or bottom of the screen be better for smaller resolutions (i.e. 640x480)? At the top it could overlap with the HUD and chatbox, and at the bottom it has the other HUD components. Which would give us those few extra pixels for the messagebox?

**Comment by Samer61** [comment]
Won't hurt if we try don't we? :P
